// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://focmfavoetrwfqawvqbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvY21mYXZvZXRyd2ZxYXd2cWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjgyMTQsImV4cCI6MjA2NDUwNDIxNH0.1StECCifLR0KxWxCZiyE8O3x7Uq8e03lqAqO6uWYDMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);